<?php
/**
 * @file
 * A simple wrapper for the Sailthru API Client.
 * https://github.com/sailthru/sailthru-php5-client
 */

/**
 * Implementation of hook_menu().
 */
function sailthru_client_menu() {
  $items['admin/settings/sailthru-client'] = array(
    'title' => 'Sailthru',
    'description' => 'Configure your Sailthru account',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sailthru_client_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'sailthru_client.admin.inc',
  );
  return $items;
}

/**
 * Constructor for Sailthru client.
 */
function sailthru_client_get_client($reveal_php_version = TRUE) {
  $api_key = variable_get('sailthru_client_api_key', '');
  $api_secret = variable_get('sailthru_client_api_secret', '');
  $api_uri = variable_get('sailthru_client_api_uri', 'https://api.sailthru.com');
  if (empty($api_key)) {
    watchdog('sailthru', 'The Sailthru API Key has not been configured. Please visit the <a href="!url">configuration page</a>.', array('!url' => url('admin/settings/sailthru-client')));
    drupal_set_message(t('Unable to connect to Sailthru, please check your settings'), 'error', FALSE);
    return FALSE;
  }
  if (empty($api_secret)) {
    watchdog('sailthru', 'The Sailthru API Secret has not been configured. Please visit the <a href="!url">configuration page</a>.', array('!url' => url('admin/settings/sailthru-client')));
    drupal_set_message(t('Unable to connect to Sailthru, please check your settings'), 'error', FALSE);
    return FALSE;
  }
  if (empty($api_uri)) {
    watchdog('sailthru', 'The Sailthru URI has not been configured. Please visit the <a href="!url">configuration page</a>.', array('!url' => url('admin/settings/sailthru-client')));
    drupal_set_message(t('Unable to connect to Sailthru, please check your settings'), 'error', FALSE);
    return FALSE;
  }

  module_load_include('php', 'sailthru_client', 'lib/sailthru/Sailthru_Util');
  module_load_include('php', 'sailthru_client', 'lib/sailthru/Sailthru_Client_Exception');
  module_load_include('php', 'sailthru_client', 'lib/sailthru/Sailthru_Client');

  return new Sailthru_Client($api_key, $api_secret, $api_uri, $reveal_php_version);
}
